### ISSUE TITLE
Leaked sensitive data

### ISSUE THREAD

**Issue by Senither** [SirArchibald97/discord-hypixel-chat#1]
Hello Archie,

You have sensitive data leaking out of your [old commits](https://github.com/SirArchibald97/discord-hypixel-chat/blob/12f06c503db24e822497934f71b777b84d1f04cf/index.js), despite changing the static values with variables in later commits GitHub will still keep a record of all changes you've made to the repository and the information still exists in the commit history.
I'd highly recommend you delete the commit, and/or change your Minecraft account password and re-generate your Discord app token since both still seem to be working as of right now.

> I was unable to contact you on Twitter or via Discord, so I'm having to do this here instead, hopefully, you can act fast so someone else doesn't get your information and decides to use it maliciously.

**Comment by SirArchibald97** [comment]
Thank you so much for the heads up, I am relatively new to GitHub and didn't realise this data was stored. I'll delete those commits now and reset the relevant details. Thanks again.

**Comment by Senither** [comment]
You're welcome, lots of people make the same mistake as you when they first start out with GitHub or git in general, just happy to be of help.

A note on the original message that I forgot to mention is that your Discord webhook secret and token was also in the original file, so you'd have to re-generate those too if you don't want random people sending messages to the webhook channel.
